name: 🐛 Bug Report
description: Report a reproducible bug or regression in Rapid v2.
labels: ["Needs: Triage :mag:"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide all the information requested. Issues that do not follow this format are likely to stall.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of what the bug is. Please include screenshots!
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Upload screenshots or images that help illustrate the issue (if applicable).
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of Rapid does this appear on? *(The version is located in the lower-right of the screen next to your OSM username/icon)*
      placeholder: ex. 1.1.8, 2.0.2
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: What browser are you seeing the problem on? What version are you running?
      placeholder: ex. Chrome v112, Safari v16.3, Edge v112, Firefox v112, etc.
  - type: input
    id: os
    attributes:
      label: The OS you're using
      placeholder: MacOS 13.2, Linux (distro), Win10/11, etc.
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Describe how to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: URL
    attributes:
      label: The browser URL at the time you encountered the bug
      description: Please copy and paste the contents of the URL bar.
      placeholder: ex. https://mapwith.ai/Rapid#background=none&datasets=fbRoads,msBuildings&map=2.00/0.0/0.0
    validations:
      required: true
  - type: input
    id: useragent
    attributes:
      label: The auto-detected useragent string for your browser (leave blank if you're manually filling this form out)
      placeholder: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
  - type: markdown
    attributes:
      value: |
        Thanks for the issue, our team will look into it as soon as possible! If you would like to work on this issue, please wait for us to decide if it's ready. The issue will be ready to work on once we remove the "needs triage" label.
