# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ main, develop, sidewalks_v1_preview ]
  pull_request:
    branches: [ main, develop, sidewalks_v1_preview ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run all
    - run: npm run test
    - env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-west-2
        RAPID_S3_BUCKET_NAME: world.ai.rapid
        RAPID_WEB_ROOT: https://mapwith.ai
        NODE_VERSION: ${{ matrix.node-version }}
      if: ${{ matrix.node-version == '16.x' }}
      run: npm run aws_deploy
