# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [ main, develop, 286-separate_cd ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run all
    - run: npm run test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup vars
      id: vars
      run: |
        echo ::set-output name=identifier::$(git rev-parse --short ${{ github.sha }})-16.x
        echo ::set-output name=distdir::$(git rev-parse --short ${{ github.sha }})-16.x-dist

    - name: Prep files
      run: npm run aws_deploy
      env:
        IDENTIFIER: ${{ steps.vars.outputs.identifier }}
        DISTDIR: ${{ steps.vars.outputs.DISTDIR }}

    - name: Copy new index file to S3
      run: aws s3 cp $DISTDIR/index.html s3://world.ai.rapid/rapid/$IDENTIFIER-rapid.html --no-progress
      env:
        IDENTIFIER: ${{ steps.vars.outputs.identifier }}
        DISTDIR: ${{ steps.vars.outputs.DISTDIR }}

    - name: Copy new dist dir to S3
      run: aws s3 cp $DISTDIR s3://world.ai.rapid/$DISTDIR --recursive --no-progress
      env:
        IDENTIFIER: ${{ steps.vars.outputs.identifier }}
        DISTDIR: ${{ steps.vars.outputs.DISTDIR }}
      # run: echo "Your build is here: https://mapwith.ai/rapid/${GITHUB_SHA::8}-16.x-dist/index.html"
