# This workflow will push the iD source strings to transifex
# - requires TX_TOKEN secret to be set on GitHub
# - you can generate a token at https://www.transifex.com/user/settings/api/
# - job should fail silently if no token provided

name: transifex

on:
  push:
    branches:
      - develop

jobs:
  transifex:
    runs-on: ubuntu-latest
    environment: workflows

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install transifex-client
    - name: Create .transifexrc
      uses: DamianReeves/write-file-action@0a7fcbe1960c53fc08fe789fa4850d24885f4d84
      with:
        path: .transifexrc
        write-mode: overwrite
        contents: |
          [https://www.transifex.com]
          api_hostname = https://api.transifex.com
          hostname = https://www.transifex.com
          password = ${{secrets.TX_TOKEN}}
          username = api
    - name: Push source strings to Transifex
      run: tx push --source --no-interactive